#######################################################
# O Dockerfile gera a imagem da aplicacao

# Comandos importantes
#  docker build -t ubuntu-custom .
#  docker run -ti ubuntu-custom 
#######################################################
FROM  ubuntu:20.04
RUN apt update -y   
RUN apt install curl -y
RUN apt install  git -y
