#######################################################
# O Dockerfile gera a imagem da aplicacao

# Comandos importantes
#  docker build -t app .
#  docker run -ti app 

#######################################################
FROM  ubuntu:18.04
RUN apt update -y
RUN apt install curl -y
RUN apt install  git -y
